/**
 * *****************************************************************************
 * SignalControlPanel.java - Signal GUI class by Martin Bertrand
 *
 * Purpose: Single signal control class. Has controls for base, FM and AM
 * frequency along with with a WaveForm Control class for each Oscillator. The
 * class has a volume slider and a Start stop button. Each class calls a single
 * WavePlayer object and an ExtendedSampleProvider object.
 *
 * @author Martin Bertrand
 * @version 1.0
 * *****************************************************************************
 */
package glass.factory;

import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;

/**
 *
 * @author Martin Bertrand
 */
public class SignalControlPanel extends javax.swing.JPanel implements PropertyChangeListener {

    // Other variable declarations
    private double baseFrequency;       // basic frequency of oscillator
    private double FMFrequency;         // Frequency modulation rate in Hz of baser freq    
    private double AMFrequency;         // Amplitude modulation rate in Hz of base freq
    private double volume;              // Volume of oscillator instance
    /* Signal creation classes */
    private WavePlayer player;          // Plays the samples
    private ExtendedSampleProvider provider; // Creates the samples

    /**
     * Creates new form SignalControlPanel
     */
    @SuppressWarnings("LeakingThisInConstructor")
    public SignalControlPanel() {

        initComponents();
        volume = 0.5;                  // 50%
        // Plug in player and sample maker
        player = new WavePlayer();      // Default values
        provider = new ExtendedSampleProvider();
        player.setSampleProvider(provider);
        // property change listener to pass waveshape
        waveFormControlBaseFreq.addPropertyChangeListener(this);
        waveFormControlFM.addPropertyChangeListener(this);
        waveFormControlAM.addPropertyChangeListener(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        waveFormControlBaseFreq = new glass.factory.WaveFormControl();
        waveFormControlFM = new glass.factory.WaveFormControl();
        waveFormControlAM = new glass.factory.WaveFormControl();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jSlBaseFrequency = new javax.swing.JSlider();
        jSlFM = new javax.swing.JSlider();
        jSlAM = new javax.swing.JSlider();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSlVolume = new javax.swing.JSlider();
        jBStartStop = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLFreq = new javax.swing.JLabel();
        jLFM = new javax.swing.JLabel();
        jLAM = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "OSCILLATOR ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica", 0, 12))); // NOI18N

        jPanel2.add(waveFormControlBaseFreq);
        jPanel2.add(waveFormControlFM);
        jPanel2.add(waveFormControlAM);

        jLabel1.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FREQ");
        jLabel1.setPreferredSize(new java.awt.Dimension(80, 20));
        jPanel4.add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("FM");
        jLabel2.setPreferredSize(new java.awt.Dimension(80, 20));
        jPanel4.add(jLabel2);

        jLabel3.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("AM");
        jLabel3.setPreferredSize(new java.awt.Dimension(80, 20));
        jPanel4.add(jLabel3);

        jSlBaseFrequency.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlBaseFrequency.setValue(0);
        jSlBaseFrequency.setPreferredSize(new java.awt.Dimension(80, 300));
        jSlBaseFrequency.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jSlBaseFrequencyMouseDragged(evt);
            }
        });
        jPanel1.add(jSlBaseFrequency);

        jSlFM.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlFM.setValue(0);
        jSlFM.setPreferredSize(new java.awt.Dimension(80, 300));
        jSlFM.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jSlFMMouseDragged(evt);
            }
        });
        jPanel1.add(jSlFM);

        jSlAM.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlAM.setValue(0);
        jSlAM.setPreferredSize(new java.awt.Dimension(80, 300));
        jSlAM.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jSlAMMouseDragged(evt);
            }
        });
        jPanel1.add(jSlAM);

        jLabel5.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("MAX");
        jLabel5.setPreferredSize(new java.awt.Dimension(40, 20));

        jLabel4.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("VOL MIN");
        jLabel4.setPreferredSize(new java.awt.Dimension(40, 20));

        jSlVolume.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jSlVolumeMouseDragged(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel5Layout = new org.jdesktop.layout.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel5Layout.createSequentialGroup()
                        .add(6, 6, 6)
                        .add(jSlVolume, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 262, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(jPanel5Layout.createSequentialGroup()
                        .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 98, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 100, Short.MAX_VALUE)
                        .add(jLabel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(46, 46, 46))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel5Layout.createSequentialGroup()
                .add(5, 5, 5)
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jSlVolume, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jBStartStop.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        jBStartStop.setText("START");
        jBStartStop.setPreferredSize(new java.awt.Dimension(40, 20));
        jBStartStop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBStartStopMouseClicked(evt);
            }
        });
        jBStartStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBStartStopActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(jPanel3Layout.createSequentialGroup()
                .add(109, 109, 109)
                .add(jBStartStop, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 72, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jBStartStop, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLFreq.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        jLFreq.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLFreq.setText("0");
        jLFreq.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLFreq.setPreferredSize(new java.awt.Dimension(80, 20));
        jPanel6.add(jLFreq);

        jLFM.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        jLFM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLFM.setText("0");
        jLFM.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLFM.setPreferredSize(new java.awt.Dimension(80, 20));
        jPanel6.add(jLFM);

        jLAM.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        jLAM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLAM.setText("0");
        jLAM.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLAM.setPreferredSize(new java.awt.Dimension(80, 20));
        jPanel6.add(jLAM);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(layout.createSequentialGroup()
                            .add(jPanel6, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addContainerGap())
                        .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                .add(jPanel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(21, 21, 21)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBStartStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBStartStopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBStartStopActionPerformed

    private void jSlBaseFrequencyMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSlBaseFrequencyMouseDragged
        double value = jSlBaseFrequency.getValue();
        baseFrequency = this.logarithmicScaling(value);       // Scale it 
        provider.setBaseFrequency(baseFrequency); // Update base frequency        
        String baseFreq = String.format("%.1f", baseFrequency);
        this.jLFreq.setText(baseFreq);        // Update freq label       
    }//GEN-LAST:event_jSlBaseFrequencyMouseDragged

    private void jSlFMMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSlFMMouseDragged
        double value = jSlFM.getValue();
        FMFrequency = this.logarithmicScaling(value);      // Scale it   
        provider.setLFOFrequency(FMFrequency); // Update FM frequency        
        String FMFreq = String.format("%.1f", FMFrequency); // Update FM label
        this.jLFM.setText(FMFreq);
    }//GEN-LAST:event_jSlFMMouseDragged

    private void jSlAMMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSlAMMouseDragged
        double value = jSlAM.getValue();
        this.AMFrequency = this.logarithmicScaling(value);
        provider.setLAMFrequency(AMFrequency); // Update AM frequency        
        String AMFreq = String.format("%.1f", this.AMFrequency);;
        this.jLAM.setText(AMFreq);// Update AM label        
    }//GEN-LAST:event_jSlAMMouseDragged

    private void jSlVolumeMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSlVolumeMouseDragged
        this.volume = jSlVolume.getValue() / (double) jSlVolume.getMaximum();
        provider.setVolume(volume);
    }//GEN-LAST:event_jSlVolumeMouseDragged

    public double getVolume() {
        return this.volume;
    }

    private void jBStartStopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBStartStopMouseClicked
        if (jBStartStop.getText().equals("START")) {
            jBStartStop.setText("STOP");
            player.startPlayer(); // Starts the wave player
        } else {
            jBStartStop.setText("START");
            player.stopPlayer(); // Stops the wave player
        }
    }//GEN-LAST:event_jBStartStopMouseClicked

    public double getBaseFrequency() {
        return this.baseFrequency;
    }

    public double getFMFrequency() {
        return this.FMFrequency;
    }

    public double getAMFrequency() {
        return this.AMFrequency;
    }

    // Makes the slider value logarithmic
    private double logarithmicScaling(double value) {
        if (value <= 0.0) {
            return 0.0;
        }
        return Math.pow(10, value / 25.0);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBStartStop;
    private javax.swing.JLabel jLAM;
    private javax.swing.JLabel jLFM;
    private javax.swing.JLabel jLFreq;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSlider jSlAM;
    private javax.swing.JSlider jSlBaseFrequency;
    private javax.swing.JSlider jSlFM;
    private javax.swing.JSlider jSlVolume;
    private glass.factory.WaveFormControl waveFormControlAM;
    private glass.factory.WaveFormControl waveFormControlBaseFreq;
    private glass.factory.WaveFormControl waveFormControlFM;
    // End of variables declaration//GEN-END:variables

    @Override
    public void propertyChange(PropertyChangeEvent pce) {

        if (pce.getSource() == waveFormControlBaseFreq) {
            provider.setBaseWaveShape(waveFormControlBaseFreq.getWaveShape()); // Gets the selected wave shape of the base freq               
        } else if (pce.getSource() == waveFormControlAM) {
            provider.setLAMWaveShape(waveFormControlAM.getWaveShape());
        } else if (pce.getSource() == waveFormControlFM) {
            provider.setLFOWaveShape(waveFormControlFM.getWaveShape());
        }
    }
}
