/**
 * *****************************************************************************
 * WaveFormControl.java - Wave shape GUI helper class by Martin Bertrand
 *
 * Purpose: Returns the user selected wave form for a particular signal. Returns
 * a SINE, SQUARE, SAW wave form value to be used by base frequency, or FM or Am
 * generators
 *
 * @author Martin Bertrand
 * @version 1.0
 * *****************************************************************************
 */
package glass.factory;

import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeSupport;
import javax.swing.ButtonGroup;

/**
 * @author Martin Bertrand
 */
public class WaveFormControl extends javax.swing.JPanel {

    protected PropertyChangeSupport propertyChangeSupport;
    private WAVESHAPE waveShape; // Selected waveshape

    /**
     * Creates new form WaveFormControl
     */
    public WaveFormControl() {
        initComponents();
        ButtonGroup group = new ButtonGroup();
        group.add(jRbSAW);
        group.add(jRbSIN);
        group.add(jRbSQU);
        waveShape = WAVESHAPE.SIN;
        propertyChangeSupport = new PropertyChangeSupport(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jRbSIN = new javax.swing.JRadioButton();
        jRbSAW = new javax.swing.JRadioButton();
        jRbSQU = new javax.swing.JRadioButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SHAPE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica", 0, 12))); // NOI18N
        setFocusTraversalKeysEnabled(false);
        setMaximumSize(new java.awt.Dimension(60, 120));
        setPreferredSize(new java.awt.Dimension(80, 100));
        setRequestFocusEnabled(false);
        setSize(new java.awt.Dimension(80, 100));
        setLayout(new java.awt.GridLayout(0, 1));

        jRbSIN.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        jRbSIN.setSelected(true);
        jRbSIN.setText("SIN");
        jRbSIN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRbSINMouseClicked(evt);
            }
        });
        add(jRbSIN);

        jRbSAW.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        jRbSAW.setText("SAW");
        jRbSAW.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRbSAWMouseClicked(evt);
            }
        });
        jRbSAW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRbSAWActionPerformed(evt);
            }
        });
        add(jRbSAW);

        jRbSQU.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        jRbSQU.setText("SQU");
        jRbSQU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRbSQUMouseClicked(evt);
            }
        });
        add(jRbSQU);
    }// </editor-fold>//GEN-END:initComponents

    private void jRbSAWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRbSAWActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRbSAWActionPerformed

    private void jRbSINMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRbSINMouseClicked
        WAVESHAPE oldShape = waveShape;
        waveShape = WAVESHAPE.SIN;
        propertyChangeSupport.firePropertyChange("MyShapeProperty", oldShape, waveShape);


    }//GEN-LAST:event_jRbSINMouseClicked

    private void jRbSAWMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRbSAWMouseClicked
        WAVESHAPE oldShape = waveShape;
        waveShape = WAVESHAPE.SAW;
        propertyChangeSupport.firePropertyChange("MyShapeProperty", oldShape, waveShape);
    }//GEN-LAST:event_jRbSAWMouseClicked

    private void jRbSQUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRbSQUMouseClicked
        WAVESHAPE oldShape = waveShape;
        waveShape = WAVESHAPE.SQU;
        propertyChangeSupport.firePropertyChange("MyShapeProperty", oldShape, waveShape);
    }//GEN-LAST:event_jRbSQUMouseClicked

    public WAVESHAPE getWaveShape() {
        return waveShape;
    }

    public void addPropertyChangeListener(PropertyChangeListener listener) {
        propertyChangeSupport.addPropertyChangeListener(listener);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JRadioButton jRbSAW;
    private javax.swing.JRadioButton jRbSIN;
    private javax.swing.JRadioButton jRbSQU;
    // End of variables declaration//GEN-END:variables
}
